title: Eu que Criei
email: guilhermerodrigues1921@gmail.com
description: computer engineer studant blog, for my research
theme: minima

# social links
github_username:  GuilhermeRdS1921 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
